export const category = [
  {
    id: 0,
    title: "Solo Travel",
    img: "../img/categories/solo.jpg",
  },
  {
    id: 1,
    title: "Mount Travel",
    img: "../img/categories/mount.jpg",
  },
  {
    id: 2,
    title: "Jungal Travel",
    img: "../img/categories/jungal.jpg",
  },
  {
    id: 3,
    title: "Road Travel",
    img: "../img/categories/road.jpg",
  },
  {
    id: 4,
    title: "Osean Travel",
    img: "../img/categories/osean.jpg",
  },
  {
    id: 6,
    title: "Old City Travel",
    img: "../img/categories/old-city.jpg",
  },
  {
    id: 7,
    title: "Sea Travel",
    img: "../img/categories/sea.jpg",
  },
];

export const featuredExplore = [
  {
    id: 0,
    img: "./img/featured-posts/img-1.jpg",
    altText: "img",
    title: "The Golden Sands of Florida and clifornia",
    text: "Lorem ipsum dolor sit amet, con turadip iscingelit. In sed etdonec purus viverra. Sit justo velit, eu sed",
    subtitle: "Solo Travel",
    autorName: "Adam Smith",
  },
  {
    id: 1,
    img: "./img/featured-posts/img-2.jpg",
    altText: "img",
    title: "The Golden Sands of Florida and clifornia",
    text: "Lorem ipsum dolor sit amet, con turadip iscingelit. In sed etdonec purus viverra. Sit justo velit, eu sed",
    subtitle: "Solo Travel",
    autorName: "Vera Smith",
  },
  {
    id: 2,
    img: "./img/featured-posts/img-3.jpg",
    altText: "img",
    title: "The Golden Sands of Florida and clifornia",
    text: "Lorem ipsum dolor sit amet, con turadip iscingelit. In sed etdonec purus viverra. Sit justo velit, eu sed",
    subtitle: "Solo Travel",
    autorName: "Tom Readl",
  },
  {
    id: 3,
    img: "./img/featured-posts/img-4.jpg",
    altText: "img",
    title: "The Golden Sands of Florida and clifornia",
    text: "Lorem ipsum dolor sit amet, con turadip iscingelit. In sed etdonec purus viverra. Sit justo velit, eu sed",
    subtitle: "Solo Travel",
    autorName: "Riana Den",
  },
  {
    id: 4,
    img: "./img/featured-posts/img-5.jpg",
    altText: "img",
    title: "The Golden Sands of Florida and clifornia",
    text: "Lorem ipsum dolor sit amet, con turadip iscingelit. In sed etdonec purus viverra. Sit justo velit, eu sed",
    subtitle: "Solo Travel",
    autorName: "Mik Warem",
  },
  {
    id: 5,
    img: "./img/featured-posts/img-6.jpg",
    altText: "img",
    title: "The Golden Sands of Florida and clifornia",
    text: "Lorem ipsum dolor sit amet, con turadip iscingelit. In sed etdonec purus viverra. Sit justo velit, eu sed",
    subtitle: "Solo Travel",
    autorName: "Kira Soth",
  },
  {
    id: 6,
    img: "./img/featured-posts/img-2.jpg",
    altText: "img",
    title: "Mount Travel",
    text: "Lorem ipsum dolor sit amet, con turadip iscingelit.",
    subtitle: "Mount Travel",
    autorName: "Svet Dan",
  },
];
